# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170909_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ize',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
